image: WMF 5
clone_folder: c:\GOPATH\src\github.com\spf13\hugo
init:
- cmd: >-
    set PATH=%PATH%;C:\MinGW\bin;C:\GOPATH\bin

    copy c:\MinGW\bin\mingw32-make.exe c:\MinGW\bin\make.exe
environment:
  GOPATH: c:\GOPATH
install:
- cmd: >-
    gem install asciidoctor

    pip install docutils
build_script:
- cmd: make vendor
test_script:
- cmd: >-
    go env
	
    make hugo-race check

    hugo -s docs/

    hugo --renderToMemory -s docs/
