

[[constraint]]
  name = "github.com/BurntSushi/toml"
  branch = "master"

[[constraint]]
  name = "github.com/PuerkitoBio/purell"
  version = "1.1.0"

[[constraint]]
  name = "github.com/alecthomas/chroma"
  revision = "1b755a90bd109f170385cb3964f0abdfd3451145"

[[constraint]]
  branch = "master"
  name = "github.com/bep/gitmap"
  
[[constraint]]
   branch = "master"
   name = "github.com/bep/go-tocss"

[[override]]
   branch = "master"
   name = "github.com/wellington/go-libsass"
 
[[constraint]]
 name = "github.com/chaseadamsio/goorgeous"
 version = "^1.1.0"

[[constraint]]
 name = "github.com/disintegration/imaging"
 version = "~v1.2.4"

[[constraint]]
  name = "github.com/magefile/mage"
  version = "v1"

[[constraint]]
  branch = "master"
  name = "github.com/eknkc/amber"

[[constraint]]
  name = "github.com/fortytw2/leaktest"
  version = "1.1.0"

[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  version = "^1.4.0"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-immutable-radix"

[[constraint]]
  name = "github.com/jdkato/prose"
  version = "1.1.0"

[[constraint]]
  name = "github.com/kyokomi/emoji"
  version = "1.5.0"

[[constraint]]
  name = "github.com/markbates/inflect"
  revision = "a12c3aec81a6a938bf584a4bac567afed9256586"

[[constraint]]
  name = "github.com/miekg/mmark"
  version = "^1.3.6"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/mapstructure"

[[constraint]]
  name = "github.com/nicksnyder/go-i18n"
  version = "^1.10.0"

[[constraint]]
  name = "github.com/russross/blackfriday"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/afero"
  version = "^1.1.0"

[[constraint]]
  name = "github.com/spf13/cast"
  version = "^1.1.0"

[[constraint]]
  version = "^0.0.1"
  name = "github.com/spf13/cobra"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/fsync"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/jwalterweatherman"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/nitro"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  branch = "master"
  name = "github.com/olekukonko/tablewriter"

[[constraint]]
  name = "github.com/yosssi/ace"
  version = "^0.0.5"

[[constraint]]
  branch = "master"
  name = "golang.org/x/image"

[[constraint]]
  branch = "master"
  name = "golang.org/x/text"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  name = "github.com/gobwas/glob"
  version = "0.2.2"


[[constraint]]
  name = "github.com/muesli/smartcrop"
  branch = "master"


[[constraint]]
  name = "github.com/sanity-io/litter"
  version = "1.1.0"

[[constraint]]
  name = "github.com/bep/debounce"
  version = "^1.1.0"

[[constraint]]
  name = "github.com/tdewolff/minify"
  version = "^2.3.5"

[[constraint]]
  branch = "master"
  name = "github.com/BurntSushi/locker"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/hashstructure"
