[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.70.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.70.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.70.0"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.70.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/wp-login.php"
  to = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"

[[redirects]]
  from = "//blog/wp-includes/wlwmanifest.xml"
  to = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"

[[redirects]]
  from = "//cms/wp-includes/wlwmanifest.xml"
  to = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"

[[redirects]]
  from = "//wp-includes/wlwmanifest.xml"
  to = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"

[[redirects]]
  from = "//wordpress/wp-includes/wlwmanifest.xml"
  to = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"

[[redirects]]
  from = "//site/wp-includes/wlwmanifest.xml"
  to = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"

[[redirects]]
  from = "//wp/wp-includes/wlwmanifest.xml"
  to = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"

