defaults: &defaults
  docker:
      - image: bepsays/ci-goreleaser:1.14.1-t
  environment:
    CGO_ENABLED: "0"

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout:
          path: hugo
      - run:
            command: |
                git clone git@github.com:gohugoio/hugoDocs.git
                cd hugo
                go mod download
                sleep 5
                go mod verify
                go test -p 1 ./...
      - persist_to_workspace:
          root: .
          paths: .
  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /root/project
      - run:
            command: |
                    cd hugo
                    git config --global user.email "bjorn.erik.pedersen+hugoreleaser@gmail.com"
                    git config --global user.name "hugoreleaser"
                    go run -tags release main.go release -r ${CIRCLE_BRANCH}

workflows:
  version: 2
  release:
      jobs:  
        - build:
            filters:
              branches:
                only: /release-.*/
        - hold:
            type: approval
            requires:
              - build
        - release:
            context: org-global
            requires:
              - hold
