have_fun: false
memory_config:
  disabled: false
code_review:
  disable: false
  comment_severity_threshold: HIGH
  max_review_comments: -1
  pull_request_opened:
    help: true
    summary: false
    code_review: false
    include_drafts: false
ignore_patterns: []
