baseurl = "http://gohugo.io/"
MetaDataFormat = "yaml"

[params]
  description = "Documentation of Hugo, a fast and flexible static site generator built with love by spf13 and friends in Go"
  author = "Steve Francia (spf13) and friends"

[taxonomies]
  tag = "tags"
  group = "groups"

[[menu.main]]
    name = "Download Hugo"
    pre = "<i class='fa fa-download'></i>"
    url = "https://github.com/spf13/hugo/releases"
    weight = -200
[[menu.main]]
    name = "Showcase"
    pre = "<i class='fa fa-cubes'></i>"
    url = "/showcase/"
    weight = -180
[[menu.main]]
    name = "Discuss Hugo"
    pre = "<i class='fa fa-comments'></i>"
    url = "http://discuss.gohugo.io/"
    weight = -150
[[menu.main]]
    name = "About Hugo"
    identifier = "about"
    pre = "<i class='fa fa-heart'></i>"
    weight = -110
[[menu.main]]
    name = "Getting Started"
    identifier = "getting started"
    pre = "<i class='fa fa-road'></i>"
    weight = -100
[[menu.main]]
    name = "Content"
    identifier = "content"
    pre = "<i class='fa fa-file-text'></i>"
    weight = -90
[[menu.main]]
    name = "Themes"
    identifier = "themes"
    pre = "<i class='fa fa-desktop'></i>"
    weight = -85
[[menu.main]]
    name = "Templates"
    identifier = "layout"
    pre = "<i class='fa fa-columns'></i>"
    weight = -80
[[menu.main]]
    name = "Taxonomies"
    identifier = "taxonomy"
    pre = "<i class='fa fa-tags'></i>"
    weight = -70
[[menu.main]]
    name = "Extras"
    identifier = "extras"
    pre = "<i class='fa fa-gift'></i>"
    weight = -60
[[menu.main]]
    name = "Community"
    identifier = "community"
    pre = "<i class='fa fa-group'></i>"
    weight = -50
[[menu.main]]
    parent = "community"
    name = "Discussion Forum"
    url = "http://discuss.gohugo.io"
    weight = 150
[[menu.main]]
    name = "Tutorials"
    identifier = "tutorials"
    pre = "<i class='fa fa-book'></i>"
    weight = -40
[[menu.main]]
    name = "Troubleshooting"
    identifier = "troubleshooting"
    pre = "<i class='fa fa-wrench'></i>"
    weight = -30
