name: AI Detection
on:
  # Use pull_request_target instead of pull_request (we need the secrets.OPENAI_API_KEY to be available for forks)
  pull_request_target:
    types: [opened, reopened, ready_for_review, synchronize]
permissions:
  contents: read
  pull-requests: write
jobs:
  detect-ai:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: AI Watchdog
        uses: Citric-Sheep/ai-watchdog@0db4a635d309db0f8d82642130dfc33e91cf33fa # v0.2.3
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
